"""add hashed_password and membership_plan to agency_profiles

Revision ID: 777f87d6329b
Revises: 909ae5d150bc
Create Date: 2026-03-21 17:19:15.959696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777f87d6329b'
down_revision: Union[str, Sequence[str], None] = '909ae5d150bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_profiles', sa.Column('hashed_password', sa.Text(), nullable=False))
    op.add_column('agency_profiles', sa.Column('membership_plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_profiles', 'membership_plan')
    op.drop_column('agency_profiles', 'hashed_password')
    # ### end Alembic commands ###
