"""add is_active to agency_profiles

Revision ID: a5142ced3e00
Revises: 777f87d6329b
Create Date: 2026-03-21 19:01:44.190907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5142ced3e00'
down_revision: Union[str, Sequence[str], None] = '777f87d6329b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_profiles', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_profiles', 'is_active')
    # ### end Alembic commands ###
